[
  {
    full_name: "Odie Bride",
    email: "obride0@imdb.com",
    batch_no: 819,
    students: [],
  },
  {
    full_name: "Elsbeth McAlister",
    email: "emcalister1@elegantthemes.com",
    batch_no: 239,
    students: [],
  },
  {
    full_name: "Joelly Freyn",
    email: "jfreyn3@deliciousdays.com",
    batch_no: 608,
    students: [],
  },
  {
    full_name: "Mellisent Larcombe",
    email: "mlarcombe4@apple.com",
    batch_no: 968,
    students: [],
  },
  {
    full_name: "Holmes Huguenet",
    email: "hhuguenet5@instagram.com",
    batch_no: 971,
    students: [],
  },
  {
    full_name: "Aubry Ferrierio",
    email: "aferrierio6@hud.gov",
    batch_no: 814,
    students: [],
  },
  {
    full_name: "Phedra Kase",
    email: "pkase7@mac.com",
    batch_no: 860,
    students: [],
  },
  {
    full_name: "Beatrice Gilston",
    email: "bgilston8@msn.com",
    batch_no: 656,
    students: [],
  },
  {
    full_name: "Krissy Dugdale",
    email: "kdugdale9@statcounter.com",
    batch_no: 330,
    students: [],
  },
  {
    full_name: "Jozef McGairl",
    email: "jmcgairla@earthlink.net",
    batch_no: 544,
    students: [],
  },
  {
    full_name: "Ibby Sandlin",
    email: "isandlinb@newyorker.com",
    batch_no: 392,
    students: [],
  },
  {
    full_name: "Martita Kleinlerer",
    email: "mkleinlererc@tiny.cc",
    batch_no: 878,
    students: [],
  },
  {
    full_name: "Maura Asken",
    email: "maskend@wunderground.com",
    batch_no: 893,
    students: [],
  },
  {
    full_name: "Kaspar Winger",
    email: "kwingere@stanford.edu",
    batch_no: 834,
    students: [],
  },
  {
    full_name: "Orazio Kenewell",
    email: "okenewell2@google.com.br",
    batch_no: 523,
    students: [],
  },
];
